### ISSUE TITLE
Unhandled exception on Mopidy startup - OSX 10.10.3

### ISSUE THREAD

**Issue by thewusman** [sauberfred/mopidy-notifier#11]
Hi, just installed using homebrew method, doesn't seem to work with mopidy(latest) and OS X (10.10.3) - following error on mopidy launch:

ERROR    Unhandled exception in NotifierFrontend (urn:uuid:c69e0f78-c53d-412b-9944-973873e4ef5b):
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pykka/actor.py", line 191, in _actor_loop
    self.on_start()
  File "/usr/local/lib/python2.7/site-packages/mopidy_notifier/frontend.py", line 27, in on_start
    self.notify('Starting...')
TypeError: notify() takes exactly 3 arguments (2 given)

Any ideas ?

Thanks.

**Comment by jodal** [comment]
This seems to be fixed in commit 6ebe9c94a4e7debe02912bc7d618900a52230983, released in version 0.3.3 back in April.

What version of Mopidy-Notifier do you run? You can find the version number by looking in the output of the command `mopidy deps`.

**Comment by jodal** [comment]
Only now did I notice the keyword "Homebrew". I updated Mopidy-Notifier in the Mopidy Homebrew tap from 0.3.2 to 0.3.3 right now. Try running `brew update && brew upgrade` to update it.

**Comment by thewusman** [comment]
All fixed - homebrew update worked - thanks ! 

Great stuff on this project :)
