### ISSUE TITLE
Tag versions

### ISSUE THREAD

**Issue by Freso** [sauberfred/mopidy-notifier#4]
Any chance you could use tags for versions? https://aur.archlinux.org/packages/mopidy-notifier-git/ is automatically deriving the version from the Git checkout, but without a tag, its version is just incrementing by the number of commits.

Some docs on `git tag` if needed: http://git-scm.com/book/en/v2/Git-Basics-Tagging

**Comment by sauberfred** [comment]
Will be fixed with there merge of #6.
