### ISSUE TITLE
Unhandled exception on Mopidy startup

### ISSUE THREAD

**Issue by Phuzzy112** [sauberfred/mopidy-notifier#9]
OS: Debian Wheezy
Version: Mopidy-Notifier  0.3.2
              Mopidy 1.0.0

Mopidy pukes this up on startup:

ERROR    Unhandled exception in NotifierFrontend (urn:uuid:e76e0501-3a8d-4b4a-959b-5bc5e887c1c8):
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 191, in _actor_loop
    self.on_start()
  File "/usr/local/lib/python2.7/dist-packages/mopidy_notifier/frontend.py", line 27, in on_start
    self.notify('Starting...')
TypeError: notify() takes exactly 3 arguments (2 given)

Seems that its related to the use of the "subtitle" variable with notify-send. For startup and shutdown, the variable never gets passed to notify, and on playback started, its called for passing to notify, but never populated.
I was able to fix this by changing the following in frontend.py:

ln 26:

    def on_start(self):
        self.notify('Starting...', '')

    def on_stop(self):
        self.notify('Shutting down...','')

ln 40:

        elif sys.platform.startswith('linux'):
            message = song + '\\n' + artists + ' - ' + album
            subtitle = ''

Don't know if its correct, or even a good idea, but notifications are working on my system now :)

**Comment by sauberfred** [comment]
Thanks for the report! I fixed it in version 0.3.3!
